domain: "mastodon.local"

image:
  registry: docker.io
  repository: tootsuite/mastodon
  tag: v2.4.3
  pullPolicy: IfNotPresent

mastodon:
  singleUserMode: "true"
  defaultLocale: "en"
  smtpAuthMethod: "none"
  smtpOpensslVerifyMode: "none"
  smtpFromAddress: "notifications@mastodon.local"
  smtpServer: "localhost"
  smtpPort: "25"
  localHttps: "true"
  web:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
  sidekiq:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
  streaming:
    resources:
      requests:
        memory: 32Mi
        cpu: 25m

redis:
  enabled: true
  master:
    persistence:
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

postgresql:
  enabled: true
  postgresDatabase: mastodon
  persistence:
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
